// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2vuabRRT8547-GSqMezUhpuTPi6Snbg',
    appId: '1:39101208413:web:21a208a27a314ec95e7ab4',
    messagingSenderId: '39101208413',
    projectId: 'abhoy-catering',
    authDomain: 'abhoy-catering.firebaseapp.com',
    storageBucket: 'abhoy-catering.firebasestorage.app',
    measurementId: 'G-5XP2XLM1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2vuabRRT8547-GSqMezUhpuTPi6Snbg',
    appId: '1:39101208413:android:21a208a27a314ec95e7ab4',
    messagingSenderId: '39101208413',
    projectId: 'abhoy-catering',
    storageBucket: 'abhoy-catering.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2vuabRRT8547-GSqMezUhpuTPi6Snbg',
    appId: '1:39101208413:ios:21a208a27a314ec95e7ab4',
    messagingSenderId: '39101208413',
    projectId: 'abhoy-catering',
    storageBucket: 'abhoy-catering.firebasestorage.app',
    iosBundleId: 'com.example.abhoyCatering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2vuabRRT8547-GSqMezUhpuTPi6Snbg',
    appId: '1:39101208413:macos:21a208a27a314ec95e7ab4',
    messagingSenderId: '39101208413',
    projectId: 'abhoy-catering',
    storageBucket: 'abhoy-catering.firebasestorage.app',
    iosBundleId: 'com.example.abhoyCatering',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm2vuabRRT8547-GSqMezUhpuTPi6Snbg',
    appId: '1:39101208413:web:21a208a27a314ec95e7ab4',
    messagingSenderId: '39101208413',
    projectId: 'abhoy-catering',
    storageBucket: 'abhoy-catering.firebasestorage.app',
    measurementId: 'G-5XP2XLM1ZG',
  );
}
